name: Deploy

on:
  pull_request:
    branches: 'production'
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Clone the production branch
        run: |
          git clone --branch=${{ github.head_ref }} --depth=1 https://${{ github.actor }}:${{ github.token}}@github.com/${{ github.repository }} .
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@noreply.github.com

      - name: Set version on production branch
        run: |
          head_branch=${{ github.head_ref }}
          tag=${head_branch#release\/}
          version=${tag#v}
          npm version $version
          echo "::set-env name=TAG::${tag}"

      - name: Push back to production branch
        run: |
          git push https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git production
          git push https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git ${TAG}

      - name: Publish
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.npm_token }}"
          npm publish

