name: Test

on:
  pull_request:
    branches: 'production'
    types: [synchronize, opened, reopened, edited, unlocked]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the PR branch
        run: |
          git clone --branch=${{ github.head_ref }} --depth=1 https://${{ github.actor }}:${{ github.token}}@github.com/${{ github.repository }} .

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install package dependencies
        run: |
          npm ci

      - name: Test
        run: |
          npm test
